/* ── App Constants ── */

export const DOCTORS = [
  {
    id: 1,
    name: "Dr. Ananya Sharma",
    specialization: "General Physician",
    qualification: "MBBS, MD (Internal Medicine)",
    experience: 12,
    fee: 500,
    available: true,
    successfulPatients: 4200,
    rating: 4.8,
    languages: ["English", "Hindi"],
    bio: "Dr. Ananya Sharma is a highly experienced general physician specializing in preventive care, chronic disease management, and acute illnesses. She is known for her compassionate approach and thorough diagnostics.",
    timings: "Mon–Sat, 9:00 AM – 1:00 PM",
    department: "General Medicine",
  },
  {
    id: 2,
    name: "Dr. Rajesh Patel",
    specialization: "Cardiology",
    qualification: "MBBS, DM (Cardiology), FACC",
    experience: 18,
    fee: 800,
    available: true,
    successfulPatients: 6800,
    rating: 4.9,
    languages: ["English", "Hindi", "Gujarati"],
    bio: "Dr. Rajesh Patel is a senior interventional cardiologist with expertise in angioplasty, bypass surgery consultation, and heart failure management. He has performed over 3,000 cardiac procedures.",
    timings: "Mon–Fri, 10:00 AM – 4:00 PM",
    department: "Cardiology",
  },
  {
    id: 3,
    name: "Dr. Priya Menon",
    specialization: "Dermatology",
    qualification: "MBBS, MD (Dermatology), DNB",
    experience: 10,
    fee: 600,
    available: false,
    successfulPatients: 3500,
    rating: 4.7,
    languages: ["English", "Hindi", "Malayalam"],
    bio: "Dr. Priya Menon is a board-certified dermatologist treating skin conditions including eczema, psoriasis, acne, and cosmetic dermatology. She is currently on sabbatical leave.",
    timings: "Currently Unavailable",
    department: "Dermatology",
  },
  {
    id: 4,
    name: "Dr. Vikram Singh",
    specialization: "Orthopedics",
    qualification: "MBBS, MS (Orthopedics), Fellowship in Joint Replacement",
    experience: 15,
    fee: 700,
    available: true,
    successfulPatients: 5100,
    rating: 4.8,
    languages: ["English", "Hindi", "Punjabi"],
    bio: "Dr. Vikram Singh is a renowned orthopedic surgeon specializing in joint replacements, sports injuries, and spinal surgery. He has introduced minimally invasive techniques at Nova Hospital.",
    timings: "Mon–Sat, 11:00 AM – 5:00 PM",
    department: "Orthopedics",
  },
  {
    id: 5,
    name: "Dr. Neha Gupta",
    specialization: "Pediatrics",
    qualification: "MBBS, MD (Pediatrics), IAP Fellow",
    experience: 8,
    fee: 550,
    available: true,
    successfulPatients: 2800,
    rating: 4.9,
    languages: ["English", "Hindi"],
    bio: "Dr. Neha Gupta is a compassionate pediatrician with expertise in neonatal care, childhood infections, vaccination programs, and developmental assessments for children aged 0–14 years.",
    timings: "Mon–Fri, 9:00 AM – 2:00 PM",
    department: "Pediatrics",
  },
  {
    id: 6,
    name: "Dr. Arjun Reddy",
    specialization: "Neurology",
    qualification: "MBBS, DM (Neurology), FRCP",
    experience: 20,
    fee: 900,
    available: true,
    successfulPatients: 7200,
    rating: 4.9,
    languages: ["English", "Hindi", "Telugu"],
    bio: "Dr. Arjun Reddy is the Head of Neurology at Nova Hospital. He specializes in stroke treatment, epilepsy management, and neurodegenerative disorders with over two decades of clinical experience.",
    timings: "Mon–Fri, 10:00 AM – 3:00 PM",
    department: "Neurology",
  },
  {
    id: 7,
    name: "Dr. Fatima Khan",
    specialization: "Gynecology & Obstetrics",
    qualification: "MBBS, MS (OB-GYN), FRCOG",
    experience: 14,
    fee: 650,
    available: true,
    successfulPatients: 4600,
    rating: 4.8,
    languages: ["English", "Hindi", "Urdu"],
    bio: "Dr. Fatima Khan is a senior gynecologist and obstetrician specializing in high-risk pregnancies, laparoscopic surgeries, and fertility treatments. She is dedicated to women's health and wellness.",
    timings: "Mon–Sat, 9:30 AM – 3:30 PM",
    department: "Gynecology",
  },
  {
    id: 8,
    name: "Dr. Suresh Iyer",
    specialization: "Psychiatry",
    qualification: "MBBS, MD (Psychiatry), MRCPsych",
    experience: 11,
    fee: 750,
    available: true,
    successfulPatients: 3100,
    rating: 4.7,
    languages: ["English", "Hindi", "Tamil"],
    bio: "Dr. Suresh Iyer is a consultant psychiatrist specializing in anxiety, depression, bipolar disorder, and addiction recovery. He practices evidence-based therapy integrated with medication management.",
    timings: "Tue–Sat, 11:00 AM – 6:00 PM",
    department: "Mental Health",
  },
];

export const CONSULTATION_TYPES = [
  { value: "general", label: "General Consultation", desc: "Mild fever, cough, cold, body ache" },
  { value: "followup", label: "Follow-up Visit", desc: "Revisit for ongoing treatment" },
  { value: "specialist", label: "Specialist Consultation", desc: "Heart, bone, skin, or organ-specific issue" },
  { value: "pediatric", label: "Child / Pediatric", desc: "Health concern for a child (0–14 yrs)" },
  { value: "mental", label: "Mental Health", desc: "Stress, anxiety, depression, sleep issues" },
  { value: "lab-review", label: "Lab Reports Review", desc: "Doctor review of test results" },
  { value: "prescription", label: "Prescription Renewal", desc: "Renew an existing prescription" },
  { value: "emergency", label: "Urgent / Emergency", desc: "Severe pain, breathing difficulty, injury" },
];

export const SYMPTOMS = [
  "Fever",
  "Cough / Cold",
  "Headache",
  "Body Pain",
  "Sore Throat",
  "Stomach Pain",
  "Nausea / Vomiting",
  "Skin Rash / Itching",
  "Breathing Difficulty",
  "Chest Pain",
  "Joint / Back Pain",
  "Dizziness",
  "Diarrhea",
  "Fatigue / Weakness",
  "Other",
];

export const RELATIONS = [
  "Self",
  "Father",
  "Mother",
  "Spouse",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Grandparent",
  "Other Relative",
];
