"""Added meeting_link

Revision ID: 0ca97d8c14d5
Revises: b5a9e0d606a1
Create Date: 2026-02-23 13:27:29.838927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca97d8c14d5'
down_revision = 'b5a9e0d606a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')

    # ### end Alembic commands ###
