"""Add payment fields to Appointment

Revision ID: b5a9e0d606a1
Revises: 9c4d5e6f7g8h
Create Date: 2026-02-23 11:31:43.871891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a9e0d606a1'
down_revision = '9c4d5e6f7g8h'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
