"""Add meeting summary

Revision ID: fcd99aac42bb
Revises: 0ca97d8c14d5
Create Date: 2026-03-05 10:10:34.733694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd99aac42bb'
down_revision = '0ca97d8c14d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('meeting_summary')

    # ### end Alembic commands ###
